import Head from "next/head"
import Image from "next/image"
import { SSRProvider } from 'react-bootstrap';
import LoginForm from "@/components/Auth/LoginForm/LoginForm"

export default function Home() {
  return (
    <SSRProvider>
      <Head>
        <title>Jobhub | Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jobhub.ico" />
      </Head>
      <LoginForm />
    </SSRProvider>
  )
}
