import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer/Footer"
import { SSRProvider } from 'react-bootstrap';
import Talentpage from "@/components/Talentpage/Talentpage"

export default function Home() {
  return (
    <SSRProvider>
      <Head>
        <title>Jobhub | Talent Terbaik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jobhub.ico" />
      </Head>
      <Navbar />
      <Talentpage />
      <Footer />
    </SSRProvider>
  )
}
