import Head from "next/head"
import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer/Footer"
import { SSRProvider } from "react-bootstrap"
import ProfileUser from "@/components/ProfileUser/ProfileUser"

export default function Home() {
  return (
    <SSRProvider>
      <Head>
        <title>Jobhub | User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jobhub.ico" />
      </Head>
      <Navbar />
      <ProfileUser />
      <Footer />
    </SSRProvider>
  )
}
